# Generated by Django 4.2.10 on 2024-02-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_detectedframe_frame_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedframe",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdf/"),
        ),
    ]
