# Generated by Django 4.2.10 on 2024-02-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_detectedframe_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedObjectPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="pdf/")),
            ],
        ),
        migrations.RemoveField(model_name="detectedframe", name="pdf_file",),
    ]
