# Generated by Django 4.2.10 on 2024-02-08 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_detectedobjectpdf_remove_detectedframe_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectedobjectpdf",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.video",
            ),
        ),
    ]
