# Generated by Django 4.2.10 on 2024-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_detectedframe_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="detected_gif",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
        migrations.AddField(
            model_name="video",
            name="enhanced_gif",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
        migrations.AddField(
            model_name="video",
            name="file_gif",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
        migrations.AddField(
            model_name="video",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
