# Generated by Django 4.2.10 on 2024-02-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_video_detected_gif_video_enhanced_gif_video_file_gif_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="detected_gif",
            field=models.FileField(blank=True, null=True, upload_to="detected_gifs/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="enhanced_gif",
            field=models.FileField(blank=True, null=True, upload_to="enhanced_gif/"),
        ),
    ]
