# Generated by Django 4.2.10 on 2024-02-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_video_detected_gif_alter_video_enhanced_gif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file_gif",
            field=models.FileField(blank=True, null=True, upload_to="video_gifs/"),
        ),
    ]
