# Generated by Django 4.2.10 on 2024-02-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_video_file_gif"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="enhanced_file",
            field=models.FileField(blank=True, null=True, upload_to="enhanced_file/"),
        ),
    ]
